/*
Generated by npm run actiontypes
Using ../scripts/actiontypes.ts
Payload interfaces are kept in sync with Actions & Inputs defined in manifest.yml
*/
import type { CommonEvent, EventContext } from "forge-ahead";
export interface SearchPartnerPortalPayload extends CommonEvent {
  searchText: string;
  context: EventContext;
}
